export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";
export const SET_USER = "SET_USER";
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_PROJECT = "LOAD_PROJECT";
export const SHOW_NEW_INVOICE = "SHOW_NEW_INVOICE";
export const HIDE_NEW_INVOICE = "HIDE_NEW_INVOICE";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const SELECT_PROJECT = "SELECT_PROJECT";
export const SELECT_QUOTATION = "SELECT_QUOTATION";
export const LOAD_STATIC_DATA = "LOAD_STATIC_DATA";
export const SET_VIEW_MODE = "SET_VIEW_MODE";
export const SET_QUOTATION_TYPE = "SET_QUOTATION_TYPE";
export const INITIALIZE_NEW_QUOTATION = "INITIALIZE_NEW_QUOTATION";
export const EDIT_SELECTED_QUOTATION = "EDIT_SELECTED_QUOTATION";
export const ADD_MODULE_TO_SELECTED_QUOTATION = "ADD_MODULE_TO_SELECTED_QUOTATION";
export const REMOVE_MODULE_FROM_SELECTED_QUOTATION = "REMOVE_MODULE_FROM_SELECTED_QUOTATION";
export const ADD_ACTIVITY_TO_SELECTED_QUOTATION = "ADD_ACTIVITY_TO_SELECTED_QUOTATION";
export const EDIT_ACTIVITY_IN_SELECTED_QUOTATION = "EDIT_ACTIVITY_IN_SELECTED_QUOTATION";
export const REMOVE_ACTIVITY_FROM_SELECTED_QUOTATION = "REMOVE_ACTIVITY_FROM_SELECTED_QUOTATION";
export const SHOW_ACTIVITY_RESOURCE_MODAL = "SHOW_ACTIVITY_RESOURCE_MODAL";
export const ADD_RESOURCE_TO_SELECTED_QUOTATION = "ADD_RESOURCE_TO_SELECTED_QUOTATION";
export const REMOVE_RESOURCE_FROM_SELECTED_QUOTATION = "REMOVE_RESOURCE_FROM_SELECTED_QUOTATION";
export const EDIT_RESOURCE_IN_SELECTED_QUOTATION = "EDIT_RESOURCE_IN_SELECTED_QUOTATION";


