const CREATE = "CREATE";
const VIEW = "VIEW";
const EDIT = "EDIT";

const SPONSOR = "SPONSOR";
const PROVIDER = "PROVIDER";

const NAV_REPL_PROJECT_TITLE = " _%PROJTITLE%_";
const NAV_REPL_QUOTATION_CODE  = " _%QUOTCODE%_";
const NAV_REPL_PROJECT_ID = "_%PROJID%_";
const NAV_REPL_QUOTATION_ID = "_%QUOTID%_";

export const VIEW_MODES = {CREATE, VIEW, EDIT};
export const QUOTATION_TYPES = {SPONSOR, PROVIDER};
export const NAVIGATION_REPLACERS = {NAV_REPL_PROJECT_TITLE, NAV_REPL_PROJECT_ID, NAV_REPL_QUOTATION_ID, NAV_REPL_QUOTATION_CODE};